### PR TITLE
Some minor fixes, features, and depend updates

### LINKED ISSUE #103: Create Trusted Reviewer / Submitter Role
Create a role for Trusted User, that allows the user to label clips that they upload with a aimbot / no cheat option. 

This role will have privileges higher than a standard user, but lower than a moderator/admin.
This role will NOT have access to the admin dashboard.

All higher roles will have the permission to label uploaded clips as well.

### LINKED ISSUE #104: Create Cheating Label option in video submission page
Add option to label a submitted clip as 'Aimbot' or 'No Cheats' when a Trusted User (or higher privileged role) is submitting a clip.

This option should not be visible to standard users.

I'm imagining a dropdown list item where a user can select from the options to allow us to expand the types of cheats that can be labelled in the future.

### PR DESCRIPTION
**Pull request by ceriddenn**
## **Description**

- prisma and prisma client updated from 4.8 -> 4.10.1
- added TRUSTED role to roles model.
- added Cheats model.
- added cheat dropdown and checks on site.
- added multiple cheat selection support 70a9113
NOTE: default cheat will always be NOCHEAT unless specified.
## **Issues**

- Fixes #104, fixes #103

### CODE REVIEW

**Review by jaredb1011 — APPROVED** [review]
LGTM

File: apps/web/pages/submissions/upload.tsx [hunk 1]
```diff
@@ -40,14 +40,15 @@ import { useRouter } from 'next/router';
 import Head from 'next/head';
 import { prisma } from '@server/db/client';
 import { legal } from '@utils/links';
-
+type Cheat = 'NOCHEAT' | 'AIMBOT' | 'TRIGGERBOT' | 'ESP' | 'SPINBOT';
```
Comment (Huskydog9988) [inline apps/web/pages/submissions/upload.tsx:43]: why use this instead of the prisma enum type?

File: apps/web/utils/zod/gameplay.ts [hunk 2]
```diff
@@ -1,6 +1,13 @@
 import { z } from 'zod';
 import { PublicUserSchema } from './dash';
 export const GameplayTypes = z.enum(['VAL', 'CSG', 'TF2', 'APE', 'COD', 'R6S']);
+export const CheatTypes = z.enum([
+  'NOCHEAT',
+  'AIMBOT',
+  'TRIGGERBOT',
+  'ESP',
+  'SPINBOT',
+]);
```
Comment (Huskydog9988) [inline apps/web/utils/zod/gameplay.ts:10]: if this exists why not use this type in upload.tsx?

File: package.json [hunk 3]
```diff
@@ -27,5 +27,9 @@
   "engines": {
     "node": "^18.12.1"
   },
-  "packageManager": "yarn@3.3.0"
+  "packageManager": "yarn@3.3.0",
+  "dependencies": {
+    "@prisma/client": "latest",
+    "prisma": "latest"
+  }
```
Comment (Huskydog9988) [inline package.json:34]: your installing packages in the project root, i recommend you read this https://yarnpkg.com/cli/workspace
```suggestion
  "packageManager": "yarn@3.3.0"
```
(The version is also latest, which i'm strongly against but besides the point here.)

File: apps/web/pages/submissions/upload.tsx (hunk 1 above)
Comment (ceriddenn) [reply apps/web/pages/submissions/upload.tsx:43]: Since the gametypes enum defined in this file is not using the prisma enum value I used a zod enum to keep the file uniform... but both could be changed to use the corresponding prisma enum types.

File: apps/web/utils/zod/gameplay.ts (hunk 2 above)
Comment (ceriddenn) [reply apps/web/utils/zod/gameplay.ts:10]: when I tried to use CheatTypes in upload.tsx it thinks it's being used a value even when using typeof (which isn't ideal), I might just be rusty with ts but if you know what's wrong lmk.

File: package.json (hunk 3 above)
Comment (ceriddenn) [reply package.json]: (fixed)

**Review by jaredb1011 — APPROVED** [review]

File: package.json [hunk 4]
```diff
@@ -27,5 +27,9 @@
   "engines": {
     "node": "^18.12.1"
   },
-  "packageManager": "yarn@3.3.0"
+  "packageManager": "yarn@3.3.0",
+  "dependencies": {
+    "@prisma/client": "4.10.1",
+    "prisma": "4.10.1"
+  }
```
Comment (Huskydog9988) [inline package.json:34]: the problem is that your adding deps to the root `package.json` (this one)
```suggestion
  "packageManager": "yarn@3.3.0"
```

**Review by Huskydog9988 — APPROVED** [review]
